### ISSUE TITLE
Creating a new post is not working

### ISSUE THREAD

**Issue by hisashiyamaguchi** [jeyk333/CRUD-APIs#2]
I'm trying to play the app now, and although to get all posts is working fine, to create a new post is not working. Here comes my .env.

`DB_CONNECTION=mongodb+srv://mokomokomokkon:xxxx@cluster0.jrsxz.mongodb.net/poppy?retryWrites=true&w=majority
`

![スクリーンショット 2020-10-28 17 16 30](https://user-images.githubusercontent.com/43775623/97409654-571cb580-1941-11eb-9e60-27077edc736f.jpg)

![スクリーンショット 2020-10-28 17 17 15](https://user-images.githubusercontent.com/43775623/97409721-71569380-1941-11eb-875d-8d46954c190b.jpg)

![スクリーンショット 2020-10-28 17 17 32](https://user-images.githubusercontent.com/43775623/97409753-7b789200-1941-11eb-9901-ea85b75d6437.jpg)

I was assuming that my Mongo user has not been allowed to do PUT method, but the user was admin role. If you can advice me or know the workaround of this, I would like to see the detail.

**Comment by jeyk333** [comment]
Hi, 

Can you please check the logs, what error you are getting while trying to create a new post and share here?

Thanks.

**Comment by jeyk333** [comment]
Hi, I am closing the issue. As, its not active for long. Please let me know if you have any other issues

**Comment by Farbod29** [comment]
Hey Jeyanth and others,
First of thanks for wonderful description, Just one point about the post it tooks 4 hour for me to find the issue!
I got response status 400 in postman ! and here is the solution, I believe that could be the different versioning of Node.js or Mdb.
in post,js
router.post("/", (req, res) => {
console.log("get the post request" + JSON.stringify(req.body));
instead of
//const { title, description } = req.body.toString();
define your req variable like this:
var title = req.body.title.toString();
var description = req.body.description.toString();
const post = new Posts({
title,
description,
});
post
.save()
.then((resp) => res.status(201).json(resp))
.catch((err) => res.status(400).json("Request Failed"));
});

**Comment by jeyk333** [comment]
Hey Farbod, Thank you for the feedback. Yes, its been more than 7 months, since I updated this app. I will update all those libraries and will check and implement your suggestion, if its works well.
